version: '3'
services:
  app:
    build: .
    environment:
      DATABASE_URL: 'postgres://appuser:rahasia@postgres:5432/todoapp'
    volumes:
      - .:/var/www/html
    ports:
      - '8080:80'
  postgres:
    image: postgres:12
    environment:
      - POSTGRES_DB=todoapp
      - POSTGRES_USER=appuser
      - POSTGRES_PASSWORD=rahasia
